b=float(input("Enter the value of base : "))
h=float(input("Enter the value of height : "))
print("Area of Triangle : ",0.5*b*h)
print("Area of rectangle : ",b*h)
print("Area of Elips : ",3.1416*b*h)