n1=bool(input("Enter first number : "))
n2=float(input("Enter second number : "))
n3=int(input("Enter third number"))
print(type(n1))
print(type(n2))
print(type(n3))
print(f"{n2} + {n3} = {n2+n3}")
print("hello student.",end="") 
print("01731087042")